/**
 * S&P 500 全銘柄データ
 * 約500銘柄の基本情報とモック価格
 */

// セクター別の基本価格範囲
const SECTOR_PRICE_RANGES = {
    Technology: [50, 800],
    Healthcare: [40, 600],
    Financial: [30, 400],
    Consumer: [20, 350],
    Industrial: [40, 350],
    Energy: [30, 150],
    Utilities: [30, 100],
    Materials: [40, 250],
    RealEstate: [20, 150],
    Communication: [30, 400],
};

// S&P 500 全銘柄リスト（セクター分類付き）
const SP500_SYMBOLS = [
    // Technology (約70銘柄)
    { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
    { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology' },
    { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', sector: 'Technology' },
    { symbol: 'GOOG', name: 'Alphabet Inc. Class C', sector: 'Technology' },
    { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Technology' },
    { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
    { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
    { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Technology' },
    { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Technology' },
    { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Technology' },
    { symbol: 'ACN', name: 'Accenture PLC', sector: 'Technology' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
    { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology' },
    { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
    { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology' },
    { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Technology' },
    { symbol: 'IBM', name: 'IBM Corporation', sector: 'Technology' },
    { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
    { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Technology' },
    { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
    { symbol: 'MU', name: 'Micron Technology', sector: 'Technology' },
    { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
    { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
    { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
    { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology' },
    { symbol: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
    { symbol: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Technology' },
    { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Technology' },
    { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Technology' },
    { symbol: 'ROP', name: 'Roper Technologies', sector: 'Technology' },
    { symbol: 'ADSK', name: 'Autodesk Inc.', sector: 'Technology' },
    { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
    { symbol: 'APH', name: 'Amphenol Corporation', sector: 'Technology' },
    { symbol: 'CTSH', name: 'Cognizant Technology', sector: 'Technology' },
    { symbol: 'KEYS', name: 'Keysight Technologies', sector: 'Technology' },
    { symbol: 'ON', name: 'ON Semiconductor', sector: 'Technology' },
    { symbol: 'CDW', name: 'CDW Corporation', sector: 'Technology' },
    { symbol: 'MPWR', name: 'Monolithic Power', sector: 'Technology' },
    { symbol: 'FSLR', name: 'First Solar Inc.', sector: 'Technology' },
    { symbol: 'TDY', name: 'Teledyne Technologies', sector: 'Technology' },
    { symbol: 'ANSS', name: 'ANSYS Inc.', sector: 'Technology' },
    { symbol: 'TER', name: 'Teradyne Inc.', sector: 'Technology' },
    { symbol: 'ZBRA', name: 'Zebra Technologies', sector: 'Technology' },
    { symbol: 'PTC', name: 'PTC Inc.', sector: 'Technology' },
    { symbol: 'TRMB', name: 'Trimble Inc.', sector: 'Technology' },
    { symbol: 'EPAM', name: 'EPAM Systems', sector: 'Technology' },
    { symbol: 'AKAM', name: 'Akamai Technologies', sector: 'Technology' },
    { symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Technology' },
    { symbol: 'JNPR', name: 'Juniper Networks', sector: 'Technology' },
    { symbol: 'QRVO', name: 'Qorvo Inc.', sector: 'Technology' },
    { symbol: 'GEN', name: 'Gen Digital Inc.', sector: 'Technology' },
    { symbol: 'FFIV', name: 'F5 Inc.', sector: 'Technology' },
    { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Technology' },
    { symbol: 'HPQ', name: 'HP Inc.', sector: 'Technology' },
    { symbol: 'NTAP', name: 'NetApp Inc.', sector: 'Technology' },
    { symbol: 'WDC', name: 'Western Digital', sector: 'Technology' },
    { symbol: 'STX', name: 'Seagate Technology', sector: 'Technology' },
    { symbol: 'ENPH', name: 'Enphase Energy', sector: 'Technology' },
    { symbol: 'SEDG', name: 'SolarEdge Technologies', sector: 'Technology' },

    // Healthcare (約60銘柄)
    { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare' },
    { symbol: 'LLY', name: 'Eli Lilly & Co.', sector: 'Healthcare' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
    { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'Healthcare' },
    { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
    { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare' },
    { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
    { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare' },
    { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
    { symbol: 'MDT', name: 'Medtronic PLC', sector: 'Healthcare' },
    { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
    { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
    { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
    { symbol: 'REGN', name: 'Regeneron Pharmaceut.', sector: 'Healthcare' },
    { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Healthcare' },
    { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
    { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
    { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'Healthcare' },
    { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
    { symbol: 'CVS', name: 'CVS Health Corp.', sector: 'Healthcare' },
    { symbol: 'HUM', name: 'Humana Inc.', sector: 'Healthcare' },
    { symbol: 'MCK', name: 'McKesson Corporation', sector: 'Healthcare' },
    { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
    { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },
    { symbol: 'IDXX', name: 'IDEXX Laboratories', sector: 'Healthcare' },
    { symbol: 'A', name: 'Agilent Technologies', sector: 'Healthcare' },
    { symbol: 'IQV', name: 'IQVIA Holdings', sector: 'Healthcare' },
    { symbol: 'DXCM', name: 'DexCom Inc.', sector: 'Healthcare' },
    { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'Healthcare' },
    { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'Healthcare' },
    { symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Healthcare' },
    { symbol: 'MTD', name: 'Mettler-Toledo', sector: 'Healthcare' },
    { symbol: 'WAT', name: 'Waters Corporation', sector: 'Healthcare' },
    { symbol: 'HOLX', name: 'Hologic Inc.', sector: 'Healthcare' },
    { symbol: 'ALGN', name: 'Align Technology', sector: 'Healthcare' },
    { symbol: 'RMD', name: 'ResMed Inc.', sector: 'Healthcare' },
    { symbol: 'CAH', name: 'Cardinal Health', sector: 'Healthcare' },
    { symbol: 'BAX', name: 'Baxter International', sector: 'Healthcare' },
    { symbol: 'VTRS', name: 'Viatris Inc.', sector: 'Healthcare' },
    { symbol: 'CNC', name: 'Centene Corporation', sector: 'Healthcare' },
    { symbol: 'MOH', name: 'Molina Healthcare', sector: 'Healthcare' },
    { symbol: 'ILMN', name: 'Illumina Inc.', sector: 'Healthcare' },
    { symbol: 'TECH', name: 'Bio-Techne Corp.', sector: 'Healthcare' },
    { symbol: 'BIO', name: 'Bio-Rad Laboratories', sector: 'Healthcare' },
    { symbol: 'RVTY', name: 'Revvity Inc.', sector: 'Healthcare' },
    { symbol: 'COO', name: 'Cooper Companies', sector: 'Healthcare' },
    { symbol: 'XRAY', name: 'Dentsply Sirona', sector: 'Healthcare' },
    { symbol: 'DGX', name: 'Quest Diagnostics', sector: 'Healthcare' },
    { symbol: 'LH', name: 'LabCorp Holdings', sector: 'Healthcare' },
    { symbol: 'HSIC', name: 'Henry Schein Inc.', sector: 'Healthcare' },
    { symbol: 'INCY', name: 'Incyte Corporation', sector: 'Healthcare' },

    // Financial (約70銘柄)
    { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financial' },
    { symbol: 'V', name: 'Visa Inc.', sector: 'Financial' },
    { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financial' },
    { symbol: 'BAC', name: 'Bank of America', sector: 'Financial' },
    { symbol: 'WFC', name: 'Wells Fargo & Co.', sector: 'Financial' },
    { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financial' },
    { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
    { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financial' },
    { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Financial' },
    { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financial' },
    { symbol: 'AXP', name: 'American Express', sector: 'Financial' },
    { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financial' },
    { symbol: 'CB', name: 'Chubb Limited', sector: 'Financial' },
    { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financial' },
    { symbol: 'PGR', name: 'Progressive Corp.', sector: 'Financial' },
    { symbol: 'CME', name: 'CME Group Inc.', sector: 'Financial' },
    { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financial' },
    { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financial' },
    { symbol: 'AON', name: 'Aon PLC', sector: 'Financial' },
    { symbol: 'PNC', name: 'PNC Financial', sector: 'Financial' },
    { symbol: 'TFC', name: 'Truist Financial', sector: 'Financial' },
    { symbol: 'COF', name: 'Capital One Financial', sector: 'Financial' },
    { symbol: 'AIG', name: 'American Intl. Group', sector: 'Financial' },
    { symbol: 'MET', name: 'MetLife Inc.', sector: 'Financial' },
    { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Financial' },
    { symbol: 'MCO', name: 'Moody\'s Corporation', sector: 'Financial' },
    { symbol: 'TRV', name: 'Travelers Companies', sector: 'Financial' },
    { symbol: 'AJG', name: 'Arthur J. Gallagher', sector: 'Financial' },
    { symbol: 'AFL', name: 'Aflac Incorporated', sector: 'Financial' },
    { symbol: 'ALL', name: 'Allstate Corporation', sector: 'Financial' },
    { symbol: 'PRU', name: 'Prudential Financial', sector: 'Financial' },
    { symbol: 'ACGL', name: 'Arch Capital Group', sector: 'Financial' },
    { symbol: 'FIS', name: 'Fidelity National Info', sector: 'Financial' },
    { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Financial' },
    { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financial' },
    { symbol: 'STT', name: 'State Street Corp.', sector: 'Financial' },
    { symbol: 'MTB', name: 'M&T Bank Corporation', sector: 'Financial' },
    { symbol: 'TROW', name: 'T. Rowe Price', sector: 'Financial' },
    { symbol: 'NDAQ', name: 'Nasdaq Inc.', sector: 'Financial' },
    { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Financial' },
    { symbol: 'RF', name: 'Regions Financial', sector: 'Financial' },
    { symbol: 'CFG', name: 'Citizens Financial', sector: 'Financial' },
    { symbol: 'KEY', name: 'KeyCorp', sector: 'Financial' },
    { symbol: 'NTRS', name: 'Northern Trust', sector: 'Financial' },
    { symbol: 'CINF', name: 'Cincinnati Financial', sector: 'Financial' },
    { symbol: 'L', name: 'Loews Corporation', sector: 'Financial' },
    { symbol: 'RE', name: 'Everest Group Ltd', sector: 'Financial' },
    { symbol: 'WRB', name: 'W.R. Berkley Corp.', sector: 'Financial' },
    { symbol: 'DFS', name: 'Discover Financial', sector: 'Financial' },
    { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Financial' },
    { symbol: 'FRC', name: 'First Republic Bank', sector: 'Financial' },
    { symbol: 'CBOE', name: 'Cboe Global Markets', sector: 'Financial' },
    { symbol: 'RJF', name: 'Raymond James Financial', sector: 'Financial' },
    { symbol: 'BEN', name: 'Franklin Resources', sector: 'Financial' },
    { symbol: 'IVZ', name: 'Invesco Ltd.', sector: 'Financial' },
    { symbol: 'SBNY', name: 'Signature Bank', sector: 'Financial' },
    { symbol: 'ZION', name: 'Zions Bancorporation', sector: 'Financial' },
    { symbol: 'CMA', name: 'Comerica Incorporated', sector: 'Financial' },
    { symbol: 'GL', name: 'Globe Life Inc.', sector: 'Financial' },
    { symbol: 'AMP', name: 'Ameriprise Financial', sector: 'Financial' },
    { symbol: 'LNC', name: 'Lincoln National', sector: 'Financial' },

    // Consumer (約70銘柄)
    { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer' },
    { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer' },
    { symbol: 'HD', name: 'Home Depot Inc.', sector: 'Consumer' },
    { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
    { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer' },
    { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer' },
    { symbol: 'KO', name: 'Coca-Cola Company', sector: 'Consumer' },
    { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer' },
    { symbol: 'MCD', name: 'McDonald\'s Corp.', sector: 'Consumer' },
    { symbol: 'NKE', name: 'Nike Inc.', sector: 'Consumer' },
    { symbol: 'LOW', name: 'Lowe\'s Companies', sector: 'Consumer' },
    { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer' },
    { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer' },
    { symbol: 'PM', name: 'Philip Morris Intl.', sector: 'Consumer' },
    { symbol: 'MO', name: 'Altria Group Inc.', sector: 'Consumer' },
    { symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer' },
    { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer' },
    { symbol: 'EL', name: 'Estee Lauder Cos.', sector: 'Consumer' },
    { symbol: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer' },
    { symbol: 'AZO', name: 'AutoZone Inc.', sector: 'Consumer' },
    { symbol: 'ROST', name: 'Ross Stores Inc.', sector: 'Consumer' },
    { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer' },
    { symbol: 'DG', name: 'Dollar General', sector: 'Consumer' },
    { symbol: 'DLTR', name: 'Dollar Tree Inc.', sector: 'Consumer' },
    { symbol: 'DHI', name: 'D.R. Horton Inc.', sector: 'Consumer' },
    { symbol: 'LEN', name: 'Lennar Corporation', sector: 'Consumer' },
    { symbol: 'NVR', name: 'NVR Inc.', sector: 'Consumer' },
    { symbol: 'PHM', name: 'PulteGroup Inc.', sector: 'Consumer' },
    { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Consumer' },
    { symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer' },
    { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer' },
    { symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer' },
    { symbol: 'GIS', name: 'General Mills Inc.', sector: 'Consumer' },
    { symbol: 'K', name: 'Kellanova', sector: 'Consumer' },
    { symbol: 'HSY', name: 'Hershey Company', sector: 'Consumer' },
    { symbol: 'KHC', name: 'Kraft Heinz Company', sector: 'Consumer' },
    { symbol: 'ADM', name: 'Archer-Daniels-Midland', sector: 'Consumer' },
    { symbol: 'SYY', name: 'Sysco Corporation', sector: 'Consumer' },
    { symbol: 'KR', name: 'Kroger Company', sector: 'Consumer' },
    { symbol: 'WBA', name: 'Walgreens Boots', sector: 'Consumer' },
    { symbol: 'YUM', name: 'Yum! Brands Inc.', sector: 'Consumer' },
    { symbol: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer' },
    { symbol: 'DPZ', name: 'Domino\'s Pizza', sector: 'Consumer' },
    { symbol: 'DARDEN', name: 'Darden Restaurants', sector: 'Consumer' },
    { symbol: 'MAR', name: 'Marriott International', sector: 'Consumer' },
    { symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer' },
    { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer' },
    { symbol: 'MGM', name: 'MGM Resorts Intl.', sector: 'Consumer' },
    { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer' },
    { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer' },
    { symbol: 'NCLH', name: 'Norwegian Cruise Line', sector: 'Consumer' },
    { symbol: 'AAP', name: 'Advance Auto Parts', sector: 'Consumer' },
    { symbol: 'GPC', name: 'Genuine Parts Co.', sector: 'Consumer' },
    { symbol: 'BBY', name: 'Best Buy Co.', sector: 'Consumer' },
    { symbol: 'ULTA', name: 'Ulta Beauty Inc.', sector: 'Consumer' },
    { symbol: 'LULU', name: 'Lululemon Athletica', sector: 'Consumer' },
    { symbol: 'DECK', name: 'Deckers Outdoor', sector: 'Consumer' },
    { symbol: 'VFC', name: 'V.F. Corporation', sector: 'Consumer' },
    { symbol: 'PVH', name: 'PVH Corp.', sector: 'Consumer' },
    { symbol: 'RL', name: 'Ralph Lauren Corp.', sector: 'Consumer' },
    { symbol: 'TPR', name: 'Tapestry Inc.', sector: 'Consumer' },
    { symbol: 'CPRI', name: 'Capri Holdings', sector: 'Consumer' },
    { symbol: 'HAS', name: 'Hasbro Inc.', sector: 'Consumer' },
    { symbol: 'MAT', name: 'Mattel Inc.', sector: 'Consumer' },
    { symbol: 'POOL', name: 'Pool Corporation', sector: 'Consumer' },
    { symbol: 'TSCO', name: 'Tractor Supply', sector: 'Consumer' },

    // Industrial (約70銘柄)
    { symbol: 'HON', name: 'Honeywell International', sector: 'Industrial' },
    { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial' },
    { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrial' },
    { symbol: 'BA', name: 'Boeing Company', sector: 'Industrial' },
    { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrial' },
    { symbol: 'GE', name: 'General Electric', sector: 'Industrial' },
    { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
    { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrial' },
    { symbol: 'UNP', name: 'Union Pacific Corp.', sector: 'Industrial' },
    { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrial' },
    { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrial' },
    { symbol: 'MMM', name: '3M Company', sector: 'Industrial' },
    { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrial' },
    { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrial' },
    { symbol: 'ETN', name: 'Eaton Corporation', sector: 'Industrial' },
    { symbol: 'GD', name: 'General Dynamics', sector: 'Industrial' },
    { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrial' },
    { symbol: 'LHX', name: 'L3Harris Technologies', sector: 'Industrial' },
    { symbol: 'FDX', name: 'FedEx Corporation', sector: 'Industrial' },
    { symbol: 'WM', name: 'Waste Management', sector: 'Industrial' },
    { symbol: 'RSG', name: 'Republic Services', sector: 'Industrial' },
    { symbol: 'WCN', name: 'Waste Connections', sector: 'Industrial' },
    { symbol: 'CTAS', name: 'Cintas Corporation', sector: 'Industrial' },
    { symbol: 'PCAR', name: 'PACCAR Inc.', sector: 'Industrial' },
    { symbol: 'FAST', name: 'Fastenal Company', sector: 'Industrial' },
    { symbol: 'CMI', name: 'Cummins Inc.', sector: 'Industrial' },
    { symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrial' },
    { symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrial' },
    { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrial' },
    { symbol: 'OTIS', name: 'Otis Worldwide', sector: 'Industrial' },
    { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrial' },
    { symbol: 'TT', name: 'Trane Technologies', sector: 'Industrial' },
    { symbol: 'AME', name: 'AMETEK Inc.', sector: 'Industrial' },
    { symbol: 'DOV', name: 'Dover Corporation', sector: 'Industrial' },
    { symbol: 'XYL', name: 'Xylem Inc.', sector: 'Industrial' },
    { symbol: 'SWK', name: 'Stanley Black & Decker', sector: 'Industrial' },
    { symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrial' },
    { symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrial' },
    { symbol: 'CPRT', name: 'Copart Inc.', sector: 'Industrial' },
    { symbol: 'ODFL', name: 'Old Dominion Freight', sector: 'Industrial' },
    { symbol: 'JBHT', name: 'J.B. Hunt Transport', sector: 'Industrial' },
    { symbol: 'CHRW', name: 'C.H. Robinson', sector: 'Industrial' },
    { symbol: 'EXPD', name: 'Expeditors International', sector: 'Industrial' },
    { symbol: 'URI', name: 'United Rentals', sector: 'Industrial' },
    { symbol: 'GWW', name: 'W.W. Grainger', sector: 'Industrial' },
    { symbol: 'FTV', name: 'Fortive Corporation', sector: 'Industrial' },
    { symbol: 'LDOS', name: 'Leidos Holdings', sector: 'Industrial' },
    { symbol: 'PWR', name: 'Quanta Services', sector: 'Industrial' },
    { symbol: 'HWM', name: 'Howmet Aerospace', sector: 'Industrial' },
    { symbol: 'WAB', name: 'Westinghouse Air', sector: 'Industrial' },
    { symbol: 'IEX', name: 'IDEX Corporation', sector: 'Industrial' },
    { symbol: 'TXT', name: 'Textron Inc.', sector: 'Industrial' },
    { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrial' },
    { symbol: 'UAL', name: 'United Airlines', sector: 'Industrial' },
    { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrial' },
    { symbol: 'AAL', name: 'American Airlines', sector: 'Industrial' },
    { symbol: 'J', name: 'Jacobs Solutions', sector: 'Industrial' },
    { symbol: 'GNRC', name: 'Generac Holdings', sector: 'Industrial' },
    { symbol: 'NDSN', name: 'Nordson Corporation', sector: 'Industrial' },
    { symbol: 'AOS', name: 'A.O. Smith Corp.', sector: 'Industrial' },
    { symbol: 'ALLE', name: 'Allegion PLC', sector: 'Industrial' },

    // Energy (約25銘柄)
    { symbol: 'XOM', name: 'Exxon Mobil Corp.', sector: 'Energy' },
    { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
    { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
    { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
    { symbol: 'SLB', name: 'Schlumberger NV', sector: 'Energy' },
    { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
    { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
    { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
    { symbol: 'PXD', name: 'Pioneer Natural Resources', sector: 'Energy' },
    { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
    { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy' },
    { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
    { symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
    { symbol: 'HES', name: 'Hess Corporation', sector: 'Energy' },
    { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
    { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
    { symbol: 'OKE', name: 'ONEOK Inc.', sector: 'Energy' },
    { symbol: 'BKR', name: 'Baker Hughes Company', sector: 'Energy' },
    { symbol: 'TRGP', name: 'Targa Resources', sector: 'Energy' },
    { symbol: 'CTRA', name: 'Coterra Energy', sector: 'Energy' },
    { symbol: 'MRO', name: 'Marathon Oil Corp.', sector: 'Energy' },
    { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },

    // Utilities (約30銘柄)
    { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
    { symbol: 'DUK', name: 'Duke Energy Corp.', sector: 'Utilities' },
    { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
    { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
    { symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities' },
    { symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
    { symbol: 'XEL', name: 'Xcel Energy Inc.', sector: 'Utilities' },
    { symbol: 'EXC', name: 'Exelon Corporation', sector: 'Utilities' },
    { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
    { symbol: 'PEG', name: 'Public Service Enterprise', sector: 'Utilities' },
    { symbol: 'WEC', name: 'WEC Energy Group', sector: 'Utilities' },
    { symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities' },
    { symbol: 'AWK', name: 'American Water Works', sector: 'Utilities' },
    { symbol: 'EIX', name: 'Edison International', sector: 'Utilities' },
    { symbol: 'DTE', name: 'DTE Energy Company', sector: 'Utilities' },
    { symbol: 'PPL', name: 'PPL Corporation', sector: 'Utilities' },
    { symbol: 'ETR', name: 'Entergy Corporation', sector: 'Utilities' },
    { symbol: 'FE', name: 'FirstEnergy Corp.', sector: 'Utilities' },
    { symbol: 'AEE', name: 'Ameren Corporation', sector: 'Utilities' },
    { symbol: 'CMS', name: 'CMS Energy Corp.', sector: 'Utilities' },
    { symbol: 'CNP', name: 'CenterPoint Energy', sector: 'Utilities' },
    { symbol: 'EVRG', name: 'Evergy Inc.', sector: 'Utilities' },
    { symbol: 'ATO', name: 'Atmos Energy', sector: 'Utilities' },
    { symbol: 'NI', name: 'NiSource Inc.', sector: 'Utilities' },
    { symbol: 'LNT', name: 'Alliant Energy', sector: 'Utilities' },
    { symbol: 'PNW', name: 'Pinnacle West Capital', sector: 'Utilities' },
    { symbol: 'NRG', name: 'NRG Energy Inc.', sector: 'Utilities' },

    // Materials (約25銘柄)
    { symbol: 'LIN', name: 'Linde PLC', sector: 'Materials' },
    { symbol: 'APD', name: 'Air Products & Chemicals', sector: 'Materials' },
    { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'Materials' },
    { symbol: 'DD', name: 'DuPont de Nemours', sector: 'Materials' },
    { symbol: 'DOW', name: 'Dow Inc.', sector: 'Materials' },
    { symbol: 'NUE', name: 'Nucor Corporation', sector: 'Materials' },
    { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
    { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials' },
    { symbol: 'MLM', name: 'Martin Marietta', sector: 'Materials' },
    { symbol: 'PPG', name: 'PPG Industries', sector: 'Materials' },
    { symbol: 'NEM', name: 'Newmont Corporation', sector: 'Materials' },
    { symbol: 'CTVA', name: 'Corteva Inc.', sector: 'Materials' },
    { symbol: 'IFF', name: 'Intl Flavors & Fragrances', sector: 'Materials' },
    { symbol: 'ALB', name: 'Albemarle Corporation', sector: 'Materials' },
    { symbol: 'BALL', name: 'Ball Corporation', sector: 'Materials' },
    { symbol: 'PKG', name: 'Packaging Corp. of America', sector: 'Materials' },
    { symbol: 'IP', name: 'International Paper', sector: 'Materials' },
    { symbol: 'AVY', name: 'Avery Dennison', sector: 'Materials' },
    { symbol: 'EMN', name: 'Eastman Chemical', sector: 'Materials' },
    { symbol: 'CE', name: 'Celanese Corporation', sector: 'Materials' },
    { symbol: 'CF', name: 'CF Industries Holdings', sector: 'Materials' },
    { symbol: 'MOS', name: 'Mosaic Company', sector: 'Materials' },
    { symbol: 'FMC', name: 'FMC Corporation', sector: 'Materials' },
    { symbol: 'SEE', name: 'Sealed Air Corp.', sector: 'Materials' },
    { symbol: 'AMCR', name: 'Amcor PLC', sector: 'Materials' },

    // Real Estate (約30銘柄)
    { symbol: 'PLD', name: 'Prologis Inc.', sector: 'RealEstate' },
    { symbol: 'AMT', name: 'American Tower Corp.', sector: 'RealEstate' },
    { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'RealEstate' },
    { symbol: 'CCI', name: 'Crown Castle Intl.', sector: 'RealEstate' },
    { symbol: 'PSA', name: 'Public Storage', sector: 'RealEstate' },
    { symbol: 'O', name: 'Realty Income Corp.', sector: 'RealEstate' },
    { symbol: 'WELL', name: 'Welltower Inc.', sector: 'RealEstate' },
    { symbol: 'SPG', name: 'Simon Property Group', sector: 'RealEstate' },
    { symbol: 'DLR', name: 'Digital Realty Trust', sector: 'RealEstate' },
    { symbol: 'VICI', name: 'VICI Properties', sector: 'RealEstate' },
    { symbol: 'AVB', name: 'AvalonBay Communities', sector: 'RealEstate' },
    { symbol: 'EQR', name: 'Equity Residential', sector: 'RealEstate' },
    { symbol: 'CBRE', name: 'CBRE Group Inc.', sector: 'RealEstate' },
    { symbol: 'SBAC', name: 'SBA Communications', sector: 'RealEstate' },
    { symbol: 'ARE', name: 'Alexandria Real Estate', sector: 'RealEstate' },
    { symbol: 'WY', name: 'Weyerhaeuser Company', sector: 'RealEstate' },
    { symbol: 'VTR', name: 'Ventas Inc.', sector: 'RealEstate' },
    { symbol: 'EXR', name: 'Extra Space Storage', sector: 'RealEstate' },
    { symbol: 'MAA', name: 'Mid-America Apartment', sector: 'RealEstate' },
    { symbol: 'ESS', name: 'Essex Property Trust', sector: 'RealEstate' },
    { symbol: 'IRM', name: 'Iron Mountain Inc.', sector: 'RealEstate' },
    { symbol: 'INVH', name: 'Invitation Homes', sector: 'RealEstate' },
    { symbol: 'HST', name: 'Host Hotels & Resorts', sector: 'RealEstate' },
    { symbol: 'REG', name: 'Regency Centers', sector: 'RealEstate' },
    { symbol: 'KIM', name: 'Kimco Realty', sector: 'RealEstate' },
    { symbol: 'CPT', name: 'Camden Property Trust', sector: 'RealEstate' },
    { symbol: 'UDR', name: 'UDR Inc.', sector: 'RealEstate' },
    { symbol: 'BXP', name: 'Boston Properties', sector: 'RealEstate' },
    { symbol: 'PEAK', name: 'Healthpeak Properties', sector: 'RealEstate' },

    // Communication Services (約25銘柄)
    { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication' },
    { symbol: 'DIS', name: 'Walt Disney Company', sector: 'Communication' },
    { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication' },
    { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication' },
    { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication' },
    { symbol: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication' },
    { symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication' },
    { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication' },
    { symbol: 'PARA', name: 'Paramount Global', sector: 'Communication' },
    { symbol: 'FOX', name: 'Fox Corporation Class B', sector: 'Communication' },
    { symbol: 'FOXA', name: 'Fox Corporation Class A', sector: 'Communication' },
    { symbol: 'LBTYA', name: 'Liberty Global Class A', sector: 'Communication' },
    { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication' },
    { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication' },
    { symbol: 'MTCH', name: 'Match Group Inc.', sector: 'Communication' },
    { symbol: 'OMC', name: 'Omnicom Group Inc.', sector: 'Communication' },
    { symbol: 'IPG', name: 'Interpublic Group', sector: 'Communication' },
    { symbol: 'LYV', name: 'Live Nation Entertainment', sector: 'Communication' },
    { symbol: 'NWSA', name: 'News Corp. Class A', sector: 'Communication' },
    { symbol: 'NWS', name: 'News Corp. Class B', sector: 'Communication' },
];

/**
 * シンボルベースの基準価格を生成（一貫性のため）
 */
function generateBasePrice(symbol, sector) {
    const seed = symbol.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
    const range = SECTOR_PRICE_RANGES[sector] || [50, 200];
    const [min, max] = range;

    // シードベースで価格を算出
    const ratio = (seed % 100) / 100;
    return min + (max - min) * ratio;
}

/**
 * STOCK_DATA オブジェクトを生成
 */
export const STOCK_DATA = {};

SP500_SYMBOLS.forEach(({ symbol, name, sector }) => {
    STOCK_DATA[symbol] = {
        name,
        sector,
        basePrice: generateBasePrice(symbol, sector),
    };
});

/**
 * 銘柄数を取得
 */
export function getStockCount() {
    return Object.keys(STOCK_DATA).length;
}
